spring:
  application:
    name: rapidbackup-console
  
  profiles:
    active: dev
    
  datasource:
    url: jdbc:postgresql://localhost:5432/rb-console
    username: rb-console-admin
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
        format_sql: true
        ddl-auto: validate
        id:
          new_generator_mappings: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  liquibase:
    change-log: classpath:config/liquibase/changelog/master.xml


  # R2DBC Configuration for reactive database access (agents module)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rb-console
    username: rb-console-admin
    password: ${DB_PASSWORD:}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: "console:"
      use-key-prefix: true
      cache-null-values: false

  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    locale: en
    locale-resolver: fixed

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600


  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      file: src/main/docker/services.yml

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  forward-headers-strategy: native
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  servlet:
    session:
      cookie:
        name: RBSESSIONID
        http-only: true
        secure: false
        same-site: lax
        path: /

logging:
  level:
    ROOT: INFO
    com.rapidobackup.console: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n%wEx"

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when-authorized
      roles: 'ADMIN'

# Application specific configuration
console:
  version: @project.version@
      
  agent:
    heartbeat-interval: 30s
    command-timeout: 5m
    max-concurrent-connections: 1000
    long-polling:
      timeout: 30000 # 30 seconds
      max-queue-size: 100
      
  backup:
    max-concurrent-jobs: 10
    default-retention-days: 30
    
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800

  internationalization:
    default-locale: en
    supported-locales: en,fr,es

---
spring:
  config:
    activate:
      on-profile: dev
  
  h2:
    console:
      enabled: false
      
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**
    livereload:
      enabled: false

  session:
    timeout: 30m

  cache:
    type: simple  # Use Spring Boot's in-memory cache

  # Disable Redis auto-configuration in development
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

logging:
  level:
    com.rapidobackup.console: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.session: DEBUG

console:
  cors:
    allowed-origins: "*"

---
spring:
  config:
    activate:
      on-profile: prod
      
  jpa:
    show-sql: false
    
  liquibase:
    contexts: prod

  session:
    timeout: 30m
    redis:
      namespace: rapidobackup:sessions
      flush-mode: on_save

server:
  servlet:
    session:
      cookie:
        name: RBSESSIONID
        http-only: true
        secure: true
        same-site: strict
        path: /

logging:
  level:
    ROOT: INFO
    com.rapidobackup.console: INFO
    org.springframework.security: WARN
  file:
    name: logs/console.log
    max-size: 100MB
    max-history: 30

console:
  cors:
    allowed-origins: "https://secure.rapidobackup.com"
